### ISSUE TITLE
UI enhancements 

### ISSUE THREAD

**Issue by reaby** [eXpansionPluginPack/eXpansion2#71]
- [ ] Prevent opening multiple instances of same windows, instead it should update windows contents.
- [ ] Create an easy way to open new instances of widgets and windows from Plugins and GUI class.

**Comment by oliverde8** [comment]
For the first one,ok I am still thinking as sometimes it's practical to have 2 instances of the same window. 

Second one not sure I understand? It's already easy just use the window factory of the widget/window to open?

Exemple to display the help windows in the chat command, it's simply this :
 
```
$this->windowHelpFactory->create($login);
```

**Comment by oliverde8** [comment]
So we won't prevent multiple instances of the same window, we will simply add a limit. so you can't open more then  windows at the same time (no limit for widgets of course)

This works a bit more like windows anywhere else, but as the server needs to use memory for each window we will put limit so that user can't abuse

**Comment by oliverde8** [comment]
after seeing the code again, windows displayed 2 times are bugs that need fixing. it actually creates memory leakes.
